version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    env_file:
      - .env.docker


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: